### ISSUE TITLE
Submit from intel to IMF does not seem to work anymore

### ISSUE THREAD

**Issue by pmodin** [itayo/IITC-Ingress-Maxfields-Exporter#28] opened 2016-05-16 09:22 UTC
After pressing "Submit!" I'm transferred to www.ingress-maxfield.com/submit.php where I'm greeted with "Error: Nothing submitted!".

Google Chrome 50.0.2661.102 (Official Build) (64-bit)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
Tampermonkey 4.0.25
Ingress Maxfield v3.1

**Comment by itayo** [comment] 2016-05-17 07:44
Seems like they have added a radiobutton to choose if you want enl or res theme, as this is not sent from IITC-Maxfield it fails.

Fix should be avalible during next hour

**Comment by itayo** [comment] 2016-05-17 08:39
Unfortenly something else have changed.
Il look deeper into it tonight. 

This might be the cause of backend changes to block out external calls

**Comment by itayo** [comment] 2016-05-20 12:01
Closing will be in 0.1.6.1 release

**Closed by itayo** 2016-05-20 12:01 UTC
Labels: bug
